services:
  ollama:
    image: ollama/ollama:0.5.4
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - GITHUB_TOKEN=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
      - DATABASE_URL=sqlite:///./mergemind.db
      - OLLAMA_HOST=http://ollama:11434
      - OLLAMA_MODEL=llama3.2:3b
      - GITHUB_CLIENT_ID=Ov23liarpCveA9VTsC90
      - GITHUB_CLIENT_SECRET=0f848961013dbd9091c26b011570b5c20f417e9c
      - SECRET_KEY=merge-mind-secret-key-that-is-at-least-32-characters-long
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - ollama

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=merge-mind-nextauth-secret-key-32-chars
      - GITHUB_CLIENT_ID=Ov23liarpCveA9VTsC90
      - GITHUB_CLIENT_SECRET=0f848961013dbd9091c26b011570b5c20f417e9c
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    command: sh -c "npm install && npm run dev"
    depends_on:
      - backend

volumes:
  ollama_data: