"use client"

import { useState, useEffect } from "react"
import Link from "next/link"
import { useSession } from "next-auth/react"
import { Star, GitFork, ExternalLink, Loader2, Github, Code, Users } from "lucide-react"

export default function PortfolioPage() {
  const { data: session } = useSession()
  const [portfolio, setPortfolio] = useState(null)
  const [loading, setLoading] = useState(true)
  const username = session?.user?.name || "BistaDinesh03"

  useEffect(() => {
    fetch(`http://localhost:8000/api/portfolio/${username}`)
      .then(r => r.json())
      .then(d => { setPortfolio(d); setLoading(false) })
  }, [username])

  if (loading) return (
    <div className="min-h-screen bg-[#0a0a0f] flex items-center justify-center">
      <Loader2 className="w-8 h-8 animate-spin text-purple-400" />
    </div>
  )

  return (
    <div className="min-h-screen bg-[#0a0a0f] text-white">
      <nav className="border-b border-gray-800 px-6 py-4 flex items-center justify-between">
        <Link href="/" className="text-xl font-bold bg-gradient-to-r from-blue-400 to-purple-400 text-transparent bg-clip-text">MergeMind</Link>
        <div className="flex items-center gap-4">
          <Link href="/dashboard" className="text-gray-300 hover:text-white text-sm">Dashboard</Link>
          <Link href="/discover" className="text-gray-300 hover:text-white text-sm">Discover</Link>
          <Link href="/portfolio" className="text-purple-400 text-sm">Portfolio</Link>
        </div>
      </nav>

      <div className="max-w-4xl mx-auto p-6">
        {/* Profile Header */}
        <div className="flex items-center gap-6 mb-10 bg-[#111118] rounded-xl p-6 border border-gray-800">
          {portfolio?.avatar && <img src={portfolio.avatar} className="w-20 h-20 rounded-full border-2 border-purple-500" />}
          <div>
            <h1 className="text-2xl font-bold">{portfolio?.name || username}</h1>
            <p className="text-gray-400">@{username}</p>
            <p className="text-sm text-gray-500 mt-1">{portfolio?.bio || "Open source contributor"}</p>
            <div className="flex items-center gap-4 mt-3">
              <span className="flex items-center gap-1 text-sm text-gray-400"><Users className="w-4 h-4" /> {portfolio?.followers} followers</span>
              <span className="flex items-center gap-1 text-sm text-gray-400"><Code className="w-4 h-4" /> {portfolio?.public_repos} repos</span>
            </div>
          </div>
        </div>

        {/* Stats Cards */}
        <div className="grid grid-cols-3 gap-4 mb-8">
          {[
            { label: "Public Repos", value: portfolio?.public_repos || 0, icon: GitFork, color: "text-blue-400" },
            { label: "Followers", value: portfolio?.followers || 0, icon: Users, color: "text-green-400" },
            { label: "Stars Earned", value: portfolio?.repositories?.reduce((s: number, r: any) => s + r.stars, 0) || 0, icon: Star, color: "text-yellow-400" },
          ].map(s => (
            <div key={s.label} className="bg-[#111118] rounded-xl p-4 border border-gray-800 text-center">
              <s.icon className={`w-6 h-6 ${s.color} mx-auto mb-2`} />
              <p className="text-2xl font-bold">{s.value}</p>
              <p className="text-xs text-gray-400">{s.label}</p>
            </div>
          ))}
        </div>

        {/* Repos List */}
        <h2 className="text-xl font-bold mb-4">Repositories</h2>
        <div className="space-y-3">
          {portfolio?.repositories?.map((repo: any) => (
            <a key={repo.name} href={repo.url} target="_blank" rel="noopener noreferrer"
              className="flex items-center justify-between p-4 bg-[#111118] rounded-xl border border-gray-800 hover:border-gray-600 transition-all">
              <div>
                <p className="font-medium">{repo.name}</p>
                <p className="text-xs text-gray-500 mt-1">{repo.description || "No description"}</p>
                <span className="text-xs text-gray-400 mt-1 inline-block">{repo.language || "N/A"}</span>
              </div>
              <div className="flex items-center gap-3 text-sm text-gray-400">
                <span className="flex items-center gap-1"><Star className="w-4 h-4" /> {repo.stars}</span>
                <ExternalLink className="w-4 h-4" />
              </div>
            </a>
          ))}
        </div>

        <p className="text-center text-xs text-gray-600 mt-10">Generated by MergeMind</p>
      </div>
    </div>
  )
}